# Generated by Django 4.2.6 on 2023-10-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='ads',
            fields=[
                ('ad_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('adpic', models.URLField()),
            ],
        ),
    ]
