# Generated by Django 4.2.6 on 2023-10-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_remove_movie_rating_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_rating',
            name='numratings',
            field=models.IntegerField(),
        ),
    ]
