# Generated by Django 4.2.6 on 2023-10-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_movie_rating_numratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='theatre',
            fields=[
                ('theatre_id', models.AutoField(primary_key=True, serialize=False)),
                ('theatre_name', models.CharField(max_length=50)),
                ('theatre_map', models.URLField()),
                ('movies', models.ManyToManyField(related_name='theatres', to='movies.movie')),
            ],
        ),
    ]
