# Generated by Django 4.2.7 on 2023-11-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_booked_seats_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('theatres', models.ManyToManyField(related_name='locations', to='movies.theatre')),
            ],
        ),
    ]
