# Generated by Django 4.2.7 on 2023-11-15 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='theatres',
        ),
        migrations.AddField(
            model_name='theatre',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.location'),
        ),
    ]
