# Generated by Django 4.2.7 on 2023-11-15 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_theatre_loc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theatre',
            name='loc',
        ),
    ]
