# Generated by Django 4.2.7 on 2023-11-16 14:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_remove_theatre_loc'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked_seats',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
