# Generated by Django 4.2.7 on 2023-11-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0022_alter_booked_seats_seat_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked_seats',
            name='show',
            field=models.TimeField(),
        ),
    ]
