# Generated by Django 4.2.7 on 2026-08-13 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0027_alter_booked_seats_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked_seats',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booked_seats',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='booked_seats',
            name='status',
            field=models.CharField(choices=[('HOLD', 'HOLD'), ('BOOKED', 'BOOKED'), ('RELEASED', 'RELEASED')], default='BOOKED', max_length=8),
        ),
    ]
